feat: Remove jmeter configuration (#25)
* feat: Remove jmeter configuration

* feat: Enable test report from ci

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -1,7 +1,7 @@
 # This workflow will build a Java project with Maven
 # For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
 
-name: Java CI with Maven
+name: 'CI'
 
 # Controls when the action will run.
 on:
@@ -31,3 +31,8 @@ jobs:
         run: mvn test
       - name: Integration tests
         run: mvn integration-test
+      - uses: actions/upload-artifact@v2  # upload test results
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          name: test-results
+          path: target/surefire-reports/TEST*.xml
